type Author {
  id: Int @primaryKey @auto @readOnly
  name: String @required
}

type Book {
  id: Int @primaryKey @auto @readOnly
  title: String @required
  category: Category @default(value: science)
  release: String @date @required
  sold: Boolean @default(value: false)
  authorId: Int @required
}

enum Category {
  science
  poetry
}

extend type BookQuery {
  count: Int
}

type Hero {
  id: Int @primaryKey,
  name: String
  power: Int @readOnly
}
