type User {
  id: Int @primaryKey
  name: String
}

extend type User {
  foo: String
}

type Task {
  id: Int @primaryKey
  title: String
  checked: Boolean @default(value: false)
  userId: Int @required @reference(entity: User, prop: "id")
  user: User
}

type TaskQueryInterface {
  items(query: TaskQuery): [Task]
  item(id: Int!): Task
}

type UserQueryInterface {
  items(query: UserQuery): [User]
  item(id: Int!): User
}

type TaskMutationInterface {
  create(task: NewTask): Task
}

type UserMutationInterface {
  create(user: NewUser): User
}

input TaskQuery {
  id: Int
  title: String
  checked: Boolean
  userId: Int
}

input UserQuery {
  id: Int
  name: String
}

input NewTask {
  title: String
  userId: Int
}

input NewUser {
  name: String
}

type Query {
  task: TaskQueryInterface
  user: UserQueryInterface
}

type Mutation {
  task: TaskMutationInterface
  user: UserMutationInterface
}

schema {
  query: Query
  mutation: Mutation
}
